stages:
  - build
  - deploy

build_website:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/website"
      --dockerfile "${CI_PROJECT_DIR}/website/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:website"
      --cache=true

build_backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:backend"
      --cache=true

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl config get-contexts
    - kubectl config use-context alex/portfolio:portfolio
    - kubectl rollout restart deployment/website -n portfolio
    - kubectl rollout restart deployment/backend -n portfolio
