apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.atlasservers.net/alex/portfolio:backend
          resources:
            limits:
              memory: "1Gi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          env:
            - name: "REDIS_URI"
              value: redis-portfolio-prom.redis.svc.cluster.local:8070
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred-portfolio
