apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: registry.atlasservers.net/alex/portfolio:website
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
