kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redb-role
  labels:
    app: redis-enterprise
subjects:
  - kind: ServiceAccount
    name: redis-enterprise-operator
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: redb-role
  apiGroup: rbac.authorization.k8s.io
