apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis-enterprise
    redis.io/cluster: redis-portfolio
  ports:
    - port: 8001
      protocol: TCP
  type: NodePort
