kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator
  namespace: redis
subjects:
  - kind: ServiceAccount
    name: redis-enterprise-operator
    namespace: {{.Values.namespace}}
roleRef:
  kind: ClusterRole
  name: redis-enterprise-operator
  apiGroup: rbac.authorization.k8s.io
