apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis-portfolio-ui
    statefulset.kubernetes.io/pod-name: redis-portfolio-0
  ports:
    - port: 8443
      protocol: TCP
  type: NodePort
