apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: redis-portfolio
  namespace: redis
spec:
  nodes: 3
  redisEnterpriseNodeResources:
    limits:
      cpu: 100m
      memory: 250M
