apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis-enterprise
    redis.io/cluster: redis-portfolio
    redis.io/role-master: 1
    redis.io/role: node
  ports:
    - port: 8443
      protocol: TCP
  type: NodePort
