apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: redis
  namespace: {{.Values.namespace}}
spec:
  nodes: 3
  redisEnterpriseNodeResources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi
