apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: redis-portfolio
  namespace: redis
spec:
  nodes: 1
  redisEnterpriseNodeResources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi
